project:
  type: website
  resources: assets
  output-dir: docs

website:
  title: "Sport-Analytics-Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: baseball.qmd
        text: Baseball
      - href: basketball.qmd
        text: Basketball
      - href: football.qmd
        text: Football
      - href: hockey.qmd
        text: Hockey


format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true



